name: Run Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ["7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer

    - name: Install dependencies
      run: |
        # Clear composer.lock to force updating dependencies
        rm -f composer.lock
        composer install --prefer-dist --no-progress --no-suggest

    - name: Run checks
      run: composer run-script check
